# Generated by Django 5.0.2 on 2024-02-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
